%%% Start clean
clearvars
clc; close all

%%% Dependancies
run('dependancies.m')

%%% Projects to run
[BIDS_PM] = smartcache( ...
    @() bidswizard({'PM'}, '\\vs03.herseninstituut.knaw.nl\VS03-SandD-4', 'Data_BIDS'), ...
    fullfile(pwd, 'BidsFiles', 'BIDS_PM.mat'), false, {'BIDS_PM'});
% [BIDS_DROP] = smartcache( ...
%     @() bidswizard({'data-drop'}, '\\vs03.herseninstituut.knaw.nl\VS03-SandC-1\data\nin', 'rawdata'), ...
%     fullfile(pwd, 'BidsFiles', 'BIDS_DROP.mat'), false, {'BIDS_DROP'});

%% Run pipline
BIDS = BIDS_PM{1};

% % Filter data
% run_filter_bids(BIDS)

run_gedai_bids(BIDS, 'refresh', false, 'RunMode', 'StageSpecific', 'prefix', 'NEW_', ...
    'leadfielddir', fullfile(BIDS.pth, '..', 'Data_Analysis\Brainstorm_db\PM_Leadfields\data'), ...
    'scoringpath', fullfile(BIDS.pth, 'derivatives\scoring\scores\Manual_Checked') ...
    );

% %%
% %%% RUN GEDAI
% BIDS = BIDS_DROP{1}; 
% GEDAI_BIDS_tmp(BIDS, 'subjectfilter', {'drop0001'}, 'RunMode', 'StageSpecific', ...
%     'recordinglabel', '', 'refresh', false, 'removeDC', 0, ...
%     'leadfielddir', '\\vs03.herseninstituut.knaw.nl\VS03-SandD-4\PM\Data_Analysis\Brainstorm_db\DROP_Leadfields\data', ...
%     'scoringpath', fullfile(BIDS.pth, '..\derivatives\scores\final') ...
%     );
% %%
% 
% %%
% %%% RUN GEDAI
% BIDS = BIDS_PM{1};
% GEDAI_BIDS(BIDS, 'refresh', false, 'RunMode', 'StageSpecific', 'prefix', 'ZapLine_', ...
%     'leadfielddir', fullfile(BIDS.pth, '..', 'Data_Analysis\Brainstorm_db\PM_Leadfields\data'), ...
%     'scoringpath', fullfile(BIDS.pth, 'derivatives\scoring\scores\Manual_Checked') ...
%     );
% GEDAI_BIDS(BIDS, 'subjectfilter', {'hpmam006'}, 'refresh', false, 'RunMode', 'StageSpecific', ...
%     'leadfielddir', fullfile(BIDS.pth, '..', 'Data_Analysis\Brainstorm_db\Leadfield_PM\data'), ...
%     'scoringpath', fullfile(BIDS.pth, 'derivatives\scoring\scores\Manual_Checked') ...
%     );
%%















% 
% evalGEDAI(BIDS, {'StageSpecific_ICAnone_BBonly0_LCO1_BBE10_auto_PT98_BMT-2_ECTInf_SENSAI0_KC0_b1x10_b2x10_sr125'}, ...
%     'recordinglabel', '', ...
%     'scoringpath', fullfile(BIDS.pth, '..\derivatives\scores\final') ...
%     );

% %%% RUN GEDAI
% GEDAI_BIDS(BIDS, 'subjectfilter', {'hpmam006'}, 'refresh', true, 'RunMode', 'StageSpecific', ...
%     'leadfielddir', fullfile(BIDS.pth, '..', 'Data_Analysis\Brainstorm_db\Leadfield_PM\data'), ...
%     'scoringpath', fullfile(BIDS.pth, 'derivatives\scoring\scores\Manual_Checked'), ...
%     'sfppath', fullfile(BIDS.pth, '..', 'Data_collection') ...
%     );

% GEDAI_BIDS(BIDS, 'subjectfilter', {'hpmam006'}, 'refresh', true, 'RunMode', 'StageSpecific', ...
%     'prefix', 'EGI256Head_', ...
%     'leadfielddir', fullfile(BIDS.pth, '..', 'Data_Analysis\Brainstorm_db\NetsEGI\data\EGI256_NoWarp\@intra\headmodel_surf_openmeeg.mat'), ...
%     'scoringpath', fullfile(BIDS.pth, 'derivatives\scoring\scores\Manual_Checked'), ...
%     'sfppath', fullfile(BIDS.pth, '..', 'Data_collection') ...
%     );
% 
% GEDAI_BIDS(BIDS, 'subjectfilter', {'hpmam006'}, 'refresh', true, 'RunMode', 'StateWise', ...
%     'leadfielddir', fullfile(BIDS.pth, '..', 'Data_Analysis\Brainstorm_db\Leadfield_PM\data'), ...
%     'scoringpath', fullfile(BIDS.pth, 'derivatives\scoring\scores\Manual_Checked'), ...
%     'sfppath', fullfile(BIDS.pth, '..', 'Data_collection') ...
%     );
% 
% r = gedai.defaultRuns();
% r{1}.GEDAIMode = 'auto-';
% GEDAI_BIDS(BIDS, 'subjectfilter', {'hpmam006'}, 'refresh', true, 'RunMode', 'WholeNight', 'runs', r, ...
%     'leadfielddir', fullfile(BIDS.pth, '..', 'Data_Analysis\Brainstorm_db\Leadfield_PM\data'), ...
%     'scoringpath', fullfile(BIDS.pth, 'derivatives\scoring\scores\Manual_Checked'), ...
%     'sfppath', fullfile(BIDS.pth, '..', 'Data_collection') ...
%     );
% 
% r = gedai.defaultRuns();
% r{1}.GEDAIMode = 'auto-';
% GEDAI_BIDS(BIDS, 'subjectfilter', {'hpmam006'}, 'refresh', true, 'RunMode', 'StageSpecific', 'runs', r, ...
%     'leadfielddir', fullfile(BIDS.pth, '..', 'Data_Analysis\Brainstorm_db\Leadfield_PM\data'), ...
%     'scoringpath', fullfile(BIDS.pth, 'derivatives\scoring\scores\Manual_Checked'), ...
%     'sfppath', fullfile(BIDS.pth, '..', 'Data_collection') ...
%     );