%%% Start clean
clearvars
clc; close all

%%% Dependancies
run('dependancies.m')

%%% Projects to run
[BIDS_PM] = smartcache( ...
    @() bidswizard({'PM'}, '\\vs03.herseninstituut.knaw.nl\VS03-SandD-4', 'Data_BIDS'), ...
    fullfile(pwd, 'BidsFiles', 'BIDS_PM.mat'), false, {'BIDS_PM'});
BIDS = BIDS_PM{1};

%%% RUN GEDAI
GEDAI_BIDS(BIDS, 'subjectfilter', {'hpmam006'}, 'RunMode', 'StageSpecific', ...
    'leadfielddir', fullfile(BIDS.pth, '..', 'Data_Analysis\Brainstorm_db\Leadfield_PM\data'), ...
    'scoringpath', fullfile(BIDS.pth, 'derivatives\scoring\scores\Manual_Checked'), ...
    'sfppath', fullfile(BIDS.pth, '..', 'Data_collection') ...
    );