function Filter = filterbank(FilterSrate, FilterType)
    
switch FilterType
    case 'DC_RCSquareFilt'

        % Remove DC shift
        % *********************************************************************
        % srateOrigFilt   = srateOrig;
        RC              = 1.0/(0.1*2*pi);
        dt              = 1.0/FilterSrate;
        alpha           = RC/(RC + dt);
        DC_filter_num   = [alpha -alpha];
        DC_filter_den   = [1 -alpha];
        Filter          = [DC_filter_num; DC_filter_den];

    case 'LN_Notch_IIR'
         
        %%% Design IIR notch filter
        lineFreq = 50; 
        margin   = 1; % How many Hz wide the notch is
        
        % Design the filter object
        Filter = designfilt('bandstopiir', ...
            'FilterOrder', 2, ...
            'HalfPowerFrequency1', lineFreq - margin, ...
            'HalfPowerFrequency2', lineFreq + margin, ...
            'SampleRate', FilterSrate);

    case 'ICA_HiPassFilt_IIR'       

        % EEG
        % ********************************************************************* 
        
        %%% Design IIR highpasss filter
        % srateOrigFilt   = srateDwn;
        passFrq         = 1.6;
        stopFrq         = 0.8;
        passRipple      = 0.05;     
        stopAtten       = 30; 
        Filter          = designfilt('highpassiir', ...
            'PassbandFrequency', passFrq, ...
            'StopbandFrequency', stopFrq, ...
            'PassbandRipple', passRipple, ...
            'StopbandAttenuation', stopAtten, ...
            'SampleRate', FilterSrate,...
            'DesignMethod','cheby2');        

    case 'EEG_HiPassFilt_IIR'       

        % EEG
        % ********************************************************************* 
        
        %%% Design IIR highpasss filter
        % srateOrigFilt   = srateDwn;
        passFrq         = 0.5;
        stopFrq         = 0.25;
        passRipple      = 0.05;     
        stopAtten       = 30; 
        Filter          = designfilt('highpassiir', ...
            'PassbandFrequency', passFrq, ...
            'StopbandFrequency', stopFrq, ...
            'PassbandRipple', passRipple, ...
            'StopbandAttenuation', stopAtten, ...
            'SampleRate', FilterSrate,...
            'DesignMethod','cheby2');
 
    case 'EEG_LoPassFilt_IIR'   

        %%% Design IIR lowpass filter
        % srateOrigFilt   =  srateOrig;
        passFrq         = 39.7;
        stopFrq         = 49.75;
        passRipple      = 0.02;     
        stopAtten       = 60; 
        Filter          = designfilt('lowpassiir', ...
            'PassbandFrequency',passFrq, ...
            'StopbandFrequency',stopFrq, ...
            'PassbandRipple',passRipple, ...
            'StopbandAttenuation',stopAtten, ...
            'SampleRate',FilterSrate,['' ...
            'DesignMethod'],'cheby2');         
        % 
        % % FIR filter 0.5 Hz - kaiser (higher cut-off to remove sweat artifacts)
        % srateOrigFilt    = srateDwn;
        % passFrq          = 0.9;
        % stopFrq          = 0.6;
        % passRipple       = 0.05;     
        % stopAtten        = 30; 
        % EEG_HiPassFilt09 = designfilt('highpassfir','PassbandFrequency',passFrq,'StopbandFrequency',stopFrq,'StopbandAttenuation',stopAtten,'PassbandRipple',passRipple,'SampleRate',srateOrigFilt,'DesignMethod','kaiser');
        
    case 'EEG_SWLoPassFilt_IIR'   

        %%% Design IIR lowpass filter
        % srateOrigFilt   =  srateOrig;
        passFrq         = 4;
        stopFrq         = 6;
        passRipple      = 0.02;     
        stopAtten       = 60; 
        Filter          = designfilt('lowpassiir', ...
            'PassbandFrequency',passFrq, ...
            'StopbandFrequency',stopFrq, ...
            'PassbandRipple',passRipple, ...
            'StopbandAttenuation',stopAtten, ...
            'SampleRate',FilterSrate,['' ...
            'DesignMethod'],'cheby2');  

    case 'EOG_HiPassFilt_IIR'                
        
        % EOG
        % ********************************************************************* 
        
        %%% Design IIR highpasss filter
        % srateOrigFilt  = srateDwn;
        passFrq        = 0.25;
        stopFrq        = 0.01;
        passRipple     = 0.05;     
        stopAtten      = 30; 
        Filter         = designfilt('highpassiir', ...
            'PassbandFrequency', passFrq, ...
            'StopbandFrequency', stopFrq, ...
            'PassbandRipple', passRipple, ...
            'StopbandAttenuation', stopAtten, ...
            'SampleRate', FilterSrate,...
            'DesignMethod','cheby2');
     
    case 'EMG_HiPassFilt_IIR'                
        
        % EMG
        % ********************************************************************* 
        
        %%% Design IIR highpasss filter
        % srateOrigFilt  = srateDwn;
        passFrq        = 25;
        stopFrq        = 20;
        passRipple     = 0.05;     
        stopAtten      = 60; 
        Filter         = designfilt('highpassiir', ...
            'PassbandFrequency', passFrq, ...
            'StopbandFrequency', stopFrq, ...
            'PassbandRipple', passRipple, ...
            'StopbandAttenuation', stopAtten, ...
            'SampleRate', FilterSrate,...
            'DesignMethod','cheby2');

    case 'EMG_LoPassFilt_IIR'                
        
        %%% Design IIR lowpasss filter
        % srateOrigFilt  = srateOrig ;
        passFrq        = 92;
        stopFrq        = 99.8;
        passRipple     = 0.05;     
        stopAtten      = 60; 
        Filter         = designfilt('lowpassiir', ...
            'PassbandFrequency', passFrq, ...
            'StopbandFrequency', stopFrq, ...
            'PassbandRipple', passRipple, ...
            'StopbandAttenuation', stopAtten, ...
            'SampleRate', FilterSrate,...
            'DesignMethod','cheby2');

    case 'EMG_NotchFilt_IIR'

        %%% Design IIR notch filter
        % srateOrigFilt   = srateOrig ;
        stopFrq         = 50;
        bw              = 1;
        passFrq1        = 48.1;
        stopFrq1        = stopFrq - bw / 2;
        stopFrq2        = stopFrq + bw / 2;
        passFrq2        = 52;
        stopAtten       = 60;
        Filter          = designfilt('bandstopiir', ...
            'PassbandFrequency1',passFrq1, ...
            'StopbandFrequency1',stopFrq1, ...
            'StopbandFrequency2',stopFrq2, ...
            'PassbandFrequency2',passFrq2, ...
            'StopbandAttenuation',stopAtten, ...
            'SampleRate',FilterSrate, ...
            'DesignMethod','butter');

    case 'EEG_NotchFilt_IIR2'

        %%% Two cascaded IIR bandstop filters: 50 Hz and 100 Hz line noise
        % Returns a cell {Filter50, Filter100} — apply filtfilt sequentially.
        % Note: 100 Hz notch requires srate > 200 Hz.
        stopAtten   = 60;
        Filter50    = designfilt('bandstopiir', ...
            'PassbandFrequency1',  48.5, ...
            'StopbandFrequency1',  49.5, ...
            'StopbandFrequency2',  50.5, ...
            'PassbandFrequency2',  51.5, ...
            'StopbandAttenuation', stopAtten, ...
            'SampleRate',          FilterSrate, ...
            'DesignMethod',        'cheby2');
        Filter = {Filter50};
        
        if FilterSrate > 200
            Filter100   = designfilt('bandstopiir', ...
                'PassbandFrequency1',  98.5, ...
                'StopbandFrequency1',  99.5, ...
                'StopbandFrequency2', 100.5, ...
                'PassbandFrequency2', 101.5, ...
                'StopbandAttenuation', stopAtten, ...
                'SampleRate',          FilterSrate, ...
                'DesignMethod',        'cheby2');
            Filter = {Filter50, Filter100};
        end
    
    % % %% Visualize filter
    % clf; [H, f] = freqz(Filter, 5000, Filter.SampleRate);
    % subplot(121); plot(f, 20*log10(abs(H)), 'LineWidth', 2); xlabel('Hz'); ylabel('dB'); xlim([45, 55]); grid on;
    % subplot(122); plot(f, abs(H)* 100, 'LineWidth', 2); xlabel('Hz'); ylabel('%'); xlim([45, 55]); grid on;
end