%%% Start clean
clearvars
clc; close all

%%% Dependancies
run('dependancies.m')

% Warning: Name is nonexistent or not a directory: C:\Github_JB\multivariate-prep\chanlocs 

% Adjusted for DM
[BIDS_DM] = smartcache( ...
    @() {bids.layout('\\vs03.herseninstituut.knaw.nl\VS03-SandD-4\DreamModulation\Data_collection', 'use_schema', 0)}, ...
    fullfile(pwd, 'BidsFiles', 'BIDS_DM.mat'), false, {'BIDS_DM'});
BIDS = BIDS_DM{1};
fails = [];

% Variables
acqlabel = '250Hz';
refresh = false;
targetsrate = 250;
removeDC = true;
noteegchannels = [49 56 107 113 129:200];
derivfolder = 'prep-ged-ica';
scoringpath = fullfile(BIDS.pth, 'derivatives\scoring\scores\Manual_Checked');
leadfieldpath = '\\vs03.herseninstituut.knaw.nl\VS03-SandD-4\PM\Data_Analysis\Brainstorm_db\NetsEGI\data\EGI128_NoWarp\@intra\headmodel_surf_openmeeg.mat'; % needs to change to general leadfiled?!
BIDS.description = []; BIDS.description.Name = 'DM';

% Descs. badchandesc is deliberately independent of filtdesc: bad channel detection is
% decided once per recording, so changing the filter settings below no longer forces a
% re-detection, and re-detecting does not invalidate the filtered files.
badchandesc = 'rawNsmp50';
filtdesc    = 'zcSig3Frq50chunk0Win8';
geddesc     = 'zcSig3Frq50chunk0Win8ged';
subjects    = {'sub-DM02'};
sessions    = {'ses-W1', 'ses-W2', 'ses-W3'};

for ises = 1%:numel(sessions)
    session = sessions(ises);
    session = sessions;

    % *** Detect flat and bad channels (before any line-noise removal)
    %     targetsrate and removeDC must match the prepare stage below, or detection and
    %     filtering see different data.
    fails.badchan = bidsfun_detect_badchans(BIDS, ...
        'subjectfilter', subjects, ...
        'sessionfilter', session, ...
        'acqlabel', acqlabel, ...
        'refresh', refresh, ...
        'derivfolder', derivfolder, ...
        'targetsrate', targetsrate, ...
        'removeDC', removeDC, ...
        'noteegchannels', noteegchannels, ...
        'badchannumsamples', 50, ...
        'sfppath', [], ...
        'desc', badchandesc);

    % *** HP filter, remove bad channels, zapline, cleanline
    fails.prep = bidsfun_hp_zap_cleanline(BIDS, ...
        'subjectfilter', subjects, ...
        'sessionfilter', session, ...
        'acqlabel', acqlabel, ...
        'refresh', refresh, ...
        'derivfolder', derivfolder, ...
        'targetsrate', targetsrate, ...
        'removeDC', removeDC, ...
        'zapline', 1, ...
        'cleanline', 1, ...
        'zapline2', 0, ...
        'zapDetectionWinsize', 8, ...
        'noisefreqs', [50], ...
        'chunkLength', 0, ...
        'zapsigma', 3, ...
        'adaptiveSigma', true, ...
        'noteegchannels', noteegchannels, ...
        'badchandesc', badchandesc, ...
        'sfppath', [], ...        
        'desc', filtdesc);

    % *** Evaluate filter success
    fails.eval = bidsfun_evalfigs(BIDS, ...
        'subjectfilter', subjects, ...
        'sessionfilter', session, ...
        'acqlabel', acqlabel, ...
        'refresh', refresh, ...
        'derivfolder', derivfolder, ...
        'scoringpath', scoringpath, ...
        'targetchannelcount', 124, ...
        'noteegchannels', noteegchannels, ...          
        'sfppath', [], ...
        'afterdesc', filtdesc);

    % *** GEDAI
    r = gedai.defaultRuns();
    fails.gedai = bidsfun_gedai(BIDS, ...
        'RunMode', 'StageSpecific', ...
        'runs', r, ...
        'acqlabel', acqlabel, ...
        'refresh', refresh, ...
        'subjectfilter', subjects, ...
        'sessionfilter', session, ...
        'geddesc', geddesc, ...
        'inputdesc', filtdesc, ... 
        'leadfielddir', leadfieldpath, ...
        'scoringpath', scoringpath, ...
        'derivfolder', derivfolder, ...      
        'sfppath', [], ...        
        'evalplots', false ...
        );

    % *** Evaluate GEDAI success
    fails.eval = bidsfun_evalfigs(BIDS, ...
        'PlotEpochOverlay', true, ...
        'PlotExponentByStage', true, ...
        'PlotSlopesTimecourse', true, ...        
        'subjectfilter', subjects, ...
        'sessionfilter', session, ...
        'avgrefbefore', true, ... 
        'acqlabel', acqlabel, ...
        'refresh', refresh, ...
        'derivfolder', derivfolder, ...
        'scoringpath', scoringpath, ...
        'sfppath', [], ...        
        'targetchannelcount', 124, ...
        'noteegchannels', noteegchannels, ...  
        'beforedesc', filtdesc, ...
        'afterdesc', geddesc);    
end

% %%% Sleep oscis
% fails.gedai = run_sleeposci_bids(BIDS, ...
%     'RunMode', 'StageSpecific', ...
%     'acqlabel', acqlabel, ...  
%     'refresh', refresh, ...
%     'subjectfilter', {subID}, ...     
%     'geddesc', 'zc2ged2sleeposci', ...
%     'inputdesc', 'zc2gedWakeBBAutoMinusFSAutoPlus', ...
%     'scoringpath', scoringpath ...
%     );

