%%% Start clean
clearvars
clc; close all

%%% Dependancies
run('dependancies.m')

%%% Projects to run
[BIDS_DROP] = smartcache( ...
    @() bidswizard({'data-drop'}, '\\vs03.herseninstituut.knaw.nl\VS03-SandC-1\data\nin', 'rawdata'), ...
    fullfile(pwd, 'BidsFiles', 'BIDS_DROP.mat'), false, {'BIDS_DROP'});
BIDS = BIDS_DROP{1}; fails = [];

% Variables
acqlabel = '';
refresh = 0;
targetsrate = 250;
removeDC = false;
derivfolder = 'prep-ged';
scoringpath = fullfile(BIDS.pth, '..\derivatives\scores\final');
leadfieldpath = '\\vs03.herseninstituut.knaw.nl\VS03-SandD-4\PM\Data_Analysis\Brainstorm_db\DROP_Leadfields\data';
BIDS.description = []; BIDS.description.Name = 'DROP';

%%% Build leadfield matrices
build_leadfield_bids(BIDS, 'ProtocolName', 'DROP_Leadfields', ...
    'QCDir', fullfile(BIDS.pth, 'derivatives\leadfields\figures\electrode-headmodel-fit'))

% ---------------
% Run per subject
for isub = 1:numel(BIDS.participants.content.participant_id)
    subID = BIDS.participants.content.participant_id{isub};

%     % *** Filter data
%     fails.zap = bidsfun_prepare_gedai(BIDS, ...
%         'acqlabel', acqlabel, ...  
%         'refresh', refresh, ...    
%         'subjectfilter', {subID}, ...     
%         'derivfolder', derivfolder, ...
%         'targetsrate', targetsrate, ...
%         'removeDC', removeDC, ...
%         'zapline', 1, ...    
%         'cleanline', 1, ...        
%         'zapline2', 0, ...
%         'desc','zc');
%     
%     % *** Evaluate filter success
%     fails.eval = eval_filt_bids(BIDS, ...
%         'acqlabel', acqlabel, ...  
%         'refresh', refresh, ...
%         'subjectfilter', {subID}, ...   
%         'derivfolder', derivfolder, ...
%         'scoringpath', scoringpath, ...
%         'filtdesc', 'zc');
    
    % *** Run GEDAI
    if strcmp(subID, 'drop0001')
%         fails.gedai = bidsfun_run_gedai(BIDS, ...
%             'RunMode', 'StageSpecific', ...
%             'acqlabel', acqlabel, ...  
%             'refresh', refresh, ...
%             'subjectfilter', {subID}, ...     
%             'geddesc', 'zc2ged', ...
%             'inputdesc', 'zc', ...
%             'leadfielddir', leadfieldpath, ...
%             'scoringpath', scoringpath ...
%             );

        % Run with wake as auto+
        r = gedai.defaultRuns();
        r{1}.GEDAIModeBB_dict(1) = "auto";   % 1 = Wake

        fails.gedai = bidsfun_run_gedai(BIDS, ...
            'RunMode', 'StageSpecific', ...
            'runs', r, ...
            'acqlabel', acqlabel, ...  
            'refresh', refresh, ...
            'subjectfilter', {subID}, ...     
            'geddesc', 'zc2gedWakeBBAuto', ...
            'inputdesc', 'zc', ...
            'leadfielddir', leadfieldpath, ...
            'scoringpath', scoringpath ...
            );

        % Run with wake as auto+
        r = gedai.defaultRuns();
        r{1}.GEDAIModeBB_dict(1) = "auto+";   % 1 = Wake

        fails.gedai = bidsfun_run_gedai(BIDS, ...
            'RunMode', 'StageSpecific', ...
            'runs', r, ...
            'acqlabel', acqlabel, ...  
            'refresh', refresh, ...
            'subjectfilter', {subID}, ...     
            'geddesc', 'zc2gedWakeBBAutoPlus', ...
            'inputdesc', 'zc', ...
            'leadfielddir', leadfieldpath, ...
            'scoringpath', scoringpath ...
            );        

        % Run with wake as auto+
        r = gedai.defaultRuns();
        r{1}.GEDAIMode_dict(1) = "auto+";   % 1 = Wake

        fails.gedai = bidsfun_run_gedai(BIDS, ...
            'RunMode', 'StageSpecific', ...
            'runs', r, ...
            'acqlabel', acqlabel, ...  
            'refresh', refresh, ...
            'subjectfilter', {subID}, ...     
            'geddesc', 'zc2gedWakeAutoPlus', ...
            'inputdesc', 'zc', ...
            'leadfielddir', leadfieldpath, ...
            'scoringpath', scoringpath ...
            );

%         % Run a second time
%         fails.gedai = bidsfun_run_gedai(BIDS, ...
%             'RunMode', 'StageSpecific', ...
%             'acqlabel', acqlabel, ...  
%             'refresh', refresh, ...
%             'subjectfilter', {subID}, ...     
%             'inputfileext', '.set', ...
%             'geddesc', 'zc2ged2ged', ...
%             'inputdesc', 'zc2ged', ...
%             'leadfielddir', leadfieldpath, ...
%             'scoringpath', scoringpath ...
%             );
    end

    % *** RunICA
end


for isub = 1% :numel(BIDS.participants.content.participant_id)
    subID = BIDS.participants.content.participant_id{isub};

    % Run with wake as auto+
    r = gedai.defaultRuns();
    r{1}.GEDAIModeBB_dict(1) = "auto-";   % 1 = Wake
    r{1}.GEDAIMode_dict(1) = "auto+";   % 1 = Wake

    fails.gedai = bidsfun_run_gedai(BIDS, ...
        'RunMode', 'StageSpecific', ...
        'runs', r, ...
        'acqlabel', acqlabel, ...  
        'refresh', refresh, ...
        'subjectfilter', {subID}, ...     
        'geddesc', 'zc2gedWakeBBAutoMinusFSAutoPlus', ...
        'inputdesc', 'zc', ...
        'leadfielddir', leadfieldpath, ...
        'scoringpath', scoringpath ...
        );

end



%%% Sleep oscis
fails.gedai = run_sleeposci_bids(BIDS, ...
    'RunMode', 'StageSpecific', ...
    'acqlabel', acqlabel, ...  
    'refresh', refresh, ...
    'subjectfilter', {subID}, ...     
    'geddesc', 'zc2ged2sleeposci', ...
    'inputdesc', 'zc2gedWakeBBAutoMinusFSAutoPlus', ...
    'scoringpath', scoringpath ...
    );


