%%% Start clean
clearvars
clc; close all

%%% Dependancies
run('dependancies.m')

%%% Projects to run
[BIDS_ERCP] = smartcache( ...
    @() bidswizard({'data-ercp'}, '\\vs03.herseninstituut.knaw.nl\VS03-SandC-1\data\nin', 'rawdata'), ...
    fullfile(pwd, 'BidsFiles', 'BIDS_ERCP.mat'), false, {'BIDS_ERCP'});
BIDS = BIDS_ERCP{1}; fails = [];

% Variables
acqlabel = '';
refresh = 0;
targetsrate = 250;
removeDC = false;
derivfolder = 'prep-ged';
scoringpath = '';
leadfieldpath = '';
BIDS.description = []; BIDS.description.Name = 'ercp';

% ---------------
% Run per subject
for isub = 1:numel(BIDS.participants.content.participant_id)
    subID = BIDS.participants.content.participant_id{isub};

    % *** Filter data
    fails.zap = bidsfun_hp_zap_cleanline(BIDS, ...
        'acqlabel', acqlabel, ...  
        'refresh', refresh, ...    
        'subjectfilter', {subID}, ...    
        'derivfolder', derivfolder, ...
        'targetsrate', targetsrate, ...
        'removeDC', removeDC, ...
        'zapline', 1, ...    
        'cleanline', 1, ...        
        'zapline2', 0, ...
        'noisefreqs', [50, 100], ...
        'desc','zc');
    
    % *** Evaluate filter success
    fails.eval = bidsfun_evalfigs(BIDS, ...
        'acqlabel', acqlabel, ...  
        'refresh', refresh, ...
        'subjectfilter', {subID}, ...
        'derivfolder', derivfolder, ...
        'scoringpath', scoringpath, ...
        'filtdesc', 'zc');
    
    % *** Run GEDAI
    fails.gedai = bidsfun_run_gedai(BIDS, ...
        'RunMode', 'StageSpecific', ...
        'acqlabel', acqlabel, ...  
        'refresh', refresh, ...
        'derivfolder', derivfolder, ...
        'subjectfilter', {subID}, ...     
        'geddesc', 'zc2ged', ...
        'inputdesc', 'zc', ...
        'leadfielddir', leadfieldpath, ...
        'scoringpath', scoringpath ...
        );

    % *** RunICA
end



% % Filter data
% fails.zap = bidsfun_hp_zap_cleanline(BIDS, ...
%     'refresh', 1, ...
%     'subjectfilter', {'ercp0003'}, ...
%     'targetsrate', 250, ...
%     'acqlabel', '', ...
%     'cleanline',0, ...
%     'removeDC',0, ...
%     'zapline', 1, ...
%     'zapline2',1, ...
%     'noisefreqs', [50, 100], ...
%     'desc','zzn50n100');
% fails.eval = bidsfun_evalfigs(BIDS, ...
%     'subjectfilter', {'ercp0003'}, ...
%     'refresh',1, ...
%     'acqlabel', '', ...        
%     'filtdesc', 'zzn50n100');
