%%% Start clean
clearvars
clc; close all

%%% Dependancies
run('dependancies.m')

%%% Projects to run
[BIDS_PM] = smartcache( ...
    @() bidswizard({'PM'}, '\\vs03.herseninstituut.knaw.nl\VS03-SandD-4', 'Data_BIDS2'), ...
    fullfile(pwd, 'BidsFiles', 'BIDS_PM.mat'), false, {'BIDS_PM'});
BIDS = BIDS_PM{1}; fails = [];

% % Filter data
% fails.zap = run_filter_bids(BIDS, ...
%     'refresh', 1, ...
%     'acqlabel', '125Hz', ...    
%     'subjectfilter', {'hpmam003'}, ...       
%     'cleanline',0, ...
%     'removeDC',1, ...
%     'zapline', 1, ...    
%     'zapline2',1, ...
%     'desc','zz')
% fails.eval = eval_filt_bids(BIDS, ...
%     'refresh', 1, ...
%     'subjectfilter', {'hpmam003'}, ...       
%     'filtdesc', 'zz')

% Filter data
fails.zap = run_filter_bids(BIDS,'refresh', 1, ...
    'subjectfilter', {'hpmam003'}, ...       
    'acqlabel', '125Hz', ...    
    'cleanline',1, ...
    'removeDC',1, ...
    'zapline', 1, ...    
    'zapline2',0, ...
    'desc','zc')
fails.eval = eval_filt_bids(BIDS, ...
    'refresh', 1, ...
    'subjectfilter', {'hpmam003'}, ...       
    'filtdesc', 'zc')

% % Run GEDAI
% fails.gedai = run_gedai_bids(BIDS, 'RunMode', 'StageSpecific', ...
%     'refresh', 1, ...
%     'geddesc', 'zz2ged', ...
%     'inputdesc', 'zz', ...
%     'leadfielddir', fullfile(BIDS.pth, '..', 'Data_Analysis\Brainstorm_db\PM_Leadfields\data'), ...
%     'scoringpath', fullfile(BIDS.pth, 'derivatives\scoring\scores\Manual_Checked') ...
%     );