%%% Start clean
clearvars
clc; close all

%%% Dependancies
run('dependancies.m')

%%% Projects to run
[BIDS_PM] = smartcache( ...
    @() bidswizard({'PM'}, '\\vs03.herseninstituut.knaw.nl\VS03-SandD-4', 'Data_BIDS2'), ...
    fullfile(pwd, 'BidsFiles', 'BIDS_PM.mat'), false, {'BIDS_PM'});
BIDS = BIDS_PM{1}; fails = [];

% Variables
acqlabel = '250Hz';
refresh = 0;
targetsrate = 250;
removeDC = true;
derivfolder = 'prep-ged';
scoringpath = fullfile(BIDS.pth, 'derivatives\scoring\scores\Manual_Checked');
leadfieldpath = fullfile(BIDS.pth, '..', 'Data_Analysis\Brainstorm_db\PM_Leadfields\data');
BIDS.description = []; BIDS.description.Name = 'PM';

% ---------------
% Run per subject
for isub = 1:numel(BIDS.participants.content.participant_id)
    subID = BIDS.participants.content.participant_id{isub};

    % *** Filter data
    fails.zap = run_filter_bids(BIDS, ...
        'acqlabel', acqlabel, ...  
        'refresh', refresh, ...    
        'subjectfilter', {subID}, ...    
        'derivfolder', derivfolder, ...
        'targetsrate', targetsrate, ...
        'removeDC', removeDC, ...
        'zapline', 1, ...    
        'cleanline', 1, ...        
        'zapline2', 0, ...
        'desc','zc');
    
    % *** Evaluate filter success
    fails.eval = eval_filt_bids(BIDS, ...
        'acqlabel', acqlabel, ...  
        'refresh', refresh, ...
        'subjectfilter', {subID}, ...
        'derivfolder', derivfolder, ...
        'scoringpath', scoringpath, ...
        'filtdesc', 'zc');
    
    % *** Run GEDAI
    fails.gedai = run_gedai_bids(BIDS, ...
        'RunMode', 'StageSpecific', ...
        'acqlabel', acqlabel, ...  
        'refresh', refresh, ...
        'derivfolder', derivfolder, ...s
        'subjectfilter', {subID}, ...     
        'geddesc', 'zc2ged', ...
        'inputdesc', 'zc', ...
        'leadfielddir', leadfieldpath, ...
        'scoringpath', scoringpath ...
        );

    % *** RunICA
end