%%% Start clean
clearvars
clc; close all

%%% Dependancies
run('dependancies.m')

%%% Projects to run
[BIDS_DROP] = smartcache( ...
    @() bidswizard({'data-drop'}, '\\vs03.herseninstituut.knaw.nl\VS03-SandC-1\data\nin', 'rawdata'), ...
    fullfile(pwd, 'BidsFiles', 'BIDS_DROP.mat'), false, {'BIDS_DROP'});
BIDS = BIDS_DROP{1}; fails = [];
BIDS.description = []; BIDS.description.Name ='DROP';

% Filter data
fails.zap = run_filter_bids(BIDS,'refresh', 0, ...
    'subjectfilter', {'drop0001'}, ...
    'acqlabel', '', ...
    'cleanline',0, ...
    'removeDC',0, ...
    'zapline', 1, ...
    'zapline2',1, ...
    'desc','zz');
fails.eval = eval_filt_bids(BIDS, ...
    'subjectfilter', {'drop0001'}, ...
    'scoringpath', fullfile(BIDS.pth, '..\derivatives\scores\final'), ...    
    'acqlabel', '', ...        
    'filtdesc', 'zz');





% Filter data
fails.zap = run_filter_bids(BIDS,'refresh', 0, ...
    'subjectfilter', {'drop0001'}, ...
    'acqlabel', '', ...
    'cleanline',1, ...
    'removeDC',0, ...
    'zapline', 1, ...
    'zapline2',0, ...
    'desc','zc');
fails.eval = eval_filt_bids(BIDS, ...
    'subjectfilter', {'drop0001'}, ...
    'scoringpath', fullfile(BIDS.pth, '..\derivatives\scores\final'), ...
    'acqlabel', '', ...    
    'filtdesc', 'zc');


% Run GEDAI
fails.ged =run_gedai_bids(BIDS, 'RunMode', 'StageSpecific', ...
    'subjectfilter', {'drop0001'}, ...
    'refresh', 0, ...
    'acqlabel', '', ...
    'geddesc', 'zz2ged', ...
    'inputdesc', 'zz', ...
    'leadfielddir', '\\vs03.herseninstituut.knaw.nl\VS03-SandD-4\PM\Data_Analysis\Brainstorm_db\DROP_Leadfields\data', ...
    'scoringpath', fullfile(BIDS.pth, '..\derivatives\scores\final') ...
    );

% Run GEDAI
fails.ged =run_gedai_bids(BIDS, ...
    'RunMode', 'StageSpecific', ...
    'subjectfilter', {'drop0001'}, ...
    'refresh', 0, ...
    'acqlabel', '', ...
    'geddesc', 'zc2ged', ...
    'inputdesc', 'zc', ...
    'leadfielddir', '\\vs03.herseninstituut.knaw.nl\VS03-SandD-4\PM\Data_Analysis\Brainstorm_db\DROP_Leadfields\data', ...
    'scoringpath', fullfile(BIDS.pth, '..\derivatives\scores\final') ...
    );







