%%% Start clean
clearvars
clc; close all

%%% Dependancies
run(['..' filesep 'dependancies.m'])

%%% Define home path
home = '\\vs03.herseninstituut.knaw.nl' % windows
% home = '/home/sleach'; % ubuntu

%%% Build BIDS structure from data folder
%%% BIDS structure contains all pathing and subject information
[BIDS_DROP] = smartcache( ...
    @() bidswizard({'data-drop'}, fullfile(home, 'VS03-SandC-1', 'data', 'nin'), 'rawdata'), ...
    fullfile(pwd, 'BidsFiles', 'BIDS_DROP.mat'), false, {'BIDS_DROP'}); 
BIDS = BIDS_DROP{1}; fails = [];

% Variables
acqlabel        = '';    % acqlabel of EEG file, leave '' if not used
refresh         = false; % re-run when outputs already exist
refreshFigures  = false; % re-run when figures alreaady exist
targetsrate     = 250;   % down-sample to this srate
removeDC        = false; % apply 0.1 Hz high-pass filter?
derivfolder     = 'prep-zc-ged'; % name of output folder within derivatives folder
scoringpath     = fullfile(BIDS.pth, '..', 'derivatives', 'scores', 'final'); % where to find scoring files
leadfieldpath   = fullfile(home, 'VS03-SandD-4', 'PM', 'Data_Analysis', 'Brainstorm_db', 'DROP_Leadfields2', 'data'); % where to find leadfield matrices
BIDS.description = []; BIDS.description.Name = 'DROP'; % some actions are project specific (e.g., chanlocs import)

% "desc" labels 
% output filenames receive a "desc" label, indicating what was done to them
badchandesc = 'hp';      % hp:  high-pass filtered
filtdesc    = 'hpzc';    % zc:  zapline-plus & cleanline
geddesc     = 'hpzcged'; % ged: gedai
icadesc     = 'pamica';  % run-pamica.py's OUT_DESC, i.e. the desc on its *_ica.mat

% Subejct and Session filter
subjects    = {'sub-drop0001'};   % {'sub-drop0001', '...'} or {} to run on all subjects
sessions    = {'ses-t1'}; % {'ses-t1', '...'} or {} to run on all sessions

% subjects = {};
% sessions = {};

defaults = [];
defaults.subjectfilter  = subjects;
defaults.sessionfilter  = sessions;
defaults.derivfolder    = derivfolder;
defaults.acqlabel       = acqlabel;
defaults = namedargs2cell(defaults);

% Slow spindles (~12 Hz, expect frontal topography)
[failSlow, GEDsigmabb] = bidsfun_ged(BIDS, defaults{:}, ...
    'keepTheseStages', [-2], ...
    'inputdesc', geddesc, ...
    'icadesc', icadesc, ...  
    'scoringpath', scoringpath, ...    
    'gedargs', {'contrast', 'spectral', 'peakfreq', 14, 'fwhm', 2.5, ...
                'refmode', 'broadband', 'segdur', 1, 'covnorm', 'trace', 'nperm', 2});


% 
% 
% % % Slow spindles (~12 Hz, expect frontal topography)
% % [failSlow, GEDslow] = bidsfun_ged(BIDS, defauls{:}, ...
% %     'inputdesc', geddesc, ...
% %     'icadesc', icadesc, ...    
% %     'gedargs', {'contrast', 'spectral', 'peakfreq', 12, 'fwhm', 2, ...
% %                 'refmode', 'neighbour', 'neighbourdist', 2, ...
% %                 'segdur', 1, 'covnorm', 'trace', 'nperm', 1000});
% % 
% % % Fast spindles (~14 Hz, expect centro-parietal topography)
% % [failFast, GEDfast] = bidsfun_ged(BIDS, defauls{:}, ...
% %     'inputdesc', geddesc, ...
% %     'icadesc', icadesc, ...     
% %     'gedargs', {'contrast', 'spectral', 'peakfreq', 14, 'fwhm', 2, ...
% %                 'refmode', 'neighbour', 'neighbourdist', 2, ...
% %                 'segdur', 1, 'covnorm', 'trace', 'nperm', 1000});
% 
% 
% 
% 
% 
% 
% 
% 
% 
% % Slow spindles (~12 Hz, expect frontal topography)
% [failSlow, GEDsigmabb] = bidsfun_ged(BIDS, defaults{:}, ...
%     'keepTheseStages', [-2], ...
%     'inputdesc', geddesc, ...
%     'icadesc', icadesc, ...  
%     'scoringpath', scoringpath, ...    
%     'gedargs', {'contrast', 'spectral', 'peakfreq', 14, 'fwhm', 2, ...
%                 'refmode', 'broadband', 'neighbourdist', 2, ...
%                 'segdur', 1, 'covnorm', 'trace', 'nperm', 2});
% plotged(GEDsigmabb(1).ged, 'ncomps', 4, 'acttype', 'wavelet_signal', 'cmap', slanCM('coolwarm', 20), 'xwindow', 50*6)
% plotged(GEDsigmabb(1).ged, 'ncomps', 4, 'acttype', 'wavelet', 'cmap', slanCM('coolwarm', 20), 'xwindow', 60*30)
% plotged(GEDsigmabb(1).ged, 'ncomps', 4, 'acttype', 'multitaper', 'cmap', slanCM('coolwarm', 20))
% 
% % Slow spindles (~12 Hz, expect frontal topography)
% [failSlow, GEDDD] = bidsfun_ged(BIDS, defaults{:}, ...
%     'keepTheseStages', [-2], ...
%     'inputdesc', geddesc, ...
%     'icadesc', icadesc, ...  
%     'scoringpath', scoringpath, ...    
%     'gedargs', {'contrast', 'spectral', 'peakfreq', 13.5, 'fwhm', 2.5, ...
%                 'refmode', 'neighbour', 'neighbourdist', 3, ...
%                 'segdur', 1, 'covnorm', 'trace', 'nperm', 2});
% 
% 
% 
% plotged(GEDsigmabb(1).ged, 'ncomps', 4, 'acttype', 'envelope', 'cmap', 'turbo')
% plotged(GEDsigmabb(1).ged, 'ncomps', 4, 'acttype', 'envelope', 'cmap', 'turbo', 'xwindow', 30*3)
% plotged(GEDsigmabb(1).ged, 'ncomps', 4, 'acttype', 'wavelet_signal', 'cmap', slanCM('coolwarm', 20), 'xwindow', 50*6)
% 
% for night = 1:5
%     plotged(GEDsigmaNB(night).ged, 'ncomps', 6, 'acttype', 'wavelet_signal', 'cmap', slanCM('coolwarm', 20), 'xwindow', 50*6)
% end
% 
% 
% 
% [failSlow, GEDsigmaNBFast] = bidsfun_ged(BIDS, defaults{:}, ...
%     'keepTheseStages', [-2], ...
%     'inputdesc', geddesc, ...
%     'icadesc', icadesc, ...  
%     'scoringpath', scoringpath, ...    
%     'gedargs', {'contrast', 'spectral', 'peakfreq', 14.5, 'fwhm', 2.5, ...
%                 'refmode', 'neighbour', 'neighbourdist', 5, ...
%                 'segdur', 1, 'covnorm', 'trace', 'nperm', 100});
% plotged(GEDsigmaNBFast(1).ged, 'ncomps', 6, 'acttype', 'wavelet_signal', 'cmap', slanCM('coolwarm', 20), 'xwindow', 50*6)
% 
% [failSlow, GEDsigmaNBSlow] = bidsfun_ged(BIDS, defaults{:}, ...
%     'keepTheseStages', [-2], ...
%     'inputdesc', geddesc, ...
%     'icadesc', icadesc, ...  
%     'scoringpath', scoringpath, ...    
%     'gedargs', {'contrast', 'spectral', 'peakfreq', 12.5, 'fwhm', 2.5, ...
%                 'refmode', 'neighbour', 'neighbourdist', 5, ...
%                 'segdur', 1, 'covnorm', 'trace', 'nperm', 100});
% plotged(GEDsigmaNBSlow(1).ged, 'ncomps', 6, 'acttype', 'wavelet_signal', 'cmap', slanCM('coolwarm', 20), 'xwindow', 50*6)
% 
% 
% % plotged(GEDsigmabb(2).ged, 'ncomps', 6)
% % plotged(GEDsigmabb(3).ged, 'ncomps', 6)
% % plotged(GEDsigmabb(4).ged, 'ncomps', 6)
% % plotged(GEDsigmabb(5).ged, 'ncomps', 6)
% 
% 
% [~, GEDsigmaBB13o5] = bidsfun_ged(BIDS, defaults{:}, ...
%     'keepTheseStages', [-2], ...
%     'inputdesc', geddesc, ...
%     'icadesc', icadesc, ...  
%     'scoringpath', scoringpath, ...    
%     'gedargs', {'contrast', 'spectral', 'peakfreq', 13.5, 'fwhm', 3, ...
%                 'refmode', 'broadband', 'neighbourdist', 2, ...
%                 'segdur', 1, 'covnorm', 'trace', 'nperm', 2});
% plotged(GEDsigmaBB13o5(1).ged, 'ncomps', 4, 'acttype', 'wavelet_signal', 'cmap', slanCM('coolwarm', 20), 'xwindow', 300)
% 
% 
% 
% 
% % result; for a night at 250 Hz it is ~0.06 GB instead of ~2.4 GB.
% v_CurrentTraces = GEDsigmaBB13o5(1).ged.comp(2,:);
% s_Fs  = 250;
% st_Cfg.v_SigmaBand      = [12 16];  % sigma band for the time-frequency step, Hz
% st_Cfg.s_SigmaRes       = 0.2;      % frequency resolution, Hz
% v_powertimecourse = f_MGT(v_CurrentTraces, s_Fs, ...
%                           st_Cfg.v_SigmaBand(1), st_Cfg.v_SigmaBand(2), ...
%                           st_Cfg.s_SigmaRes, 'meanabs');
% 
% v_Time = linspace(0, numel(v_powertimecourse)/s_Fs, numel(v_powertimecourse));
%         v_powertimecourse = detrend(v_powertimecourse, 3);
% % figure; plot(v_powertimecourse)
% figure(); range = [176359, 272000];
% [st_Abs, st_Rel] = f_IFOGeneral(v_powertimecourse(range(1):range(2)), s_Fs, [1 numel(v_powertimecourse(range(1):range(2)))]', ['C1'], true);