geddescWN = 'hpzcgedwninfgate15autoautoBB10';

rWN = gedai.wholeNightRuns('auto','auto');            % 'auto' wavelet bands, 'auto-' broadband
defaults{2} = {'sub-drop0001'};
defaults{4} = {'ses-t1'};

%% I wanat to test bb = 2s!!
rWN{1}.GEDAIBroadbandEpochSize = 10;
fails.gedaiWN = bidsfun_gedai(BIDS, defaults{:}, ...
    'runs', rWN, ...
    'RunMode', 'WholeNight', ...
    'thresholdwindow', Inf, ...                                  % s; Inf = old behaviour
    'bandopts', struct(...
        'thresh_window_aggregate', 'min', ...
        'thresh_plausibility_gate', 15), ...
    'geddesc', geddescWN, ...
    'inputdesc', filtdesc, ...
    'leadfielddir', leadfieldpath, ...
    'scoringpath', scoringpath, ...
    'evalplots', false ...
    );

%%% Step #3.1 -> Evaluate success of step #3
fails.eval = bidsfun_evalfigs(BIDS, defaults{:}, ...
    'PlotEpochOverlay', true, ...
    'PlotExponentByStage', true, ...
    'PlotSlopesTimecourse', true, ...
    'avgrefbefore', true, ...
    'avgrefafter', false, ...
    'refresh', true, ...
    'backgroundfigs', true, ...
    'scoringpath', scoringpath, ...
    'beforedesc', filtdesc, ...
    'afterdesc', geddescWN);
