%%% Start clean
clearvars
clc; close all

%%% Dependancies
run(['..' filesep 'dependancies.m'])

%%% Define home path
home = '\\vs03.herseninstituut.knaw.nl' % windows
% home = '/home/sleach'; % ubuntu

%%% Build BIDS structure from data folder
%%% BIDS structure contains all pathing and subject information
[BIDS_DM] = smartcache( ...
    @() bidswizard({'data-drop'}, fullfile(home, 'VS03-SandD-4', 'DreamModulation', 'Data_collection'), 'rawdata'), ...
    fullfile(pwd, 'BidsFiles', 'BIDS_DM.mat'), false, {'BIDS_DM'}); 
BIDS = BIDS_DM{1}; fails = [];

% Variables
acqlabel        = '250Hz';    % acqlabel of EEG file, leave '' if not used
refresh         = true; % re-run when outputs already exist
refreshFigures  = true; % re-run when figures alreaady exist
targetsrate     = 250;   % down-sample to this srate
removeDC        = false; % apply 0.1 Hz high-pass filter?
net             = 'EGI128';
noteegchannels  = [49 56 107 113 129:200]; % not EEG channels
derivfolder     = 'prep-ged-ica'; % name of output folder within derivatives folder
scoringpath     = fullfile(BIDS.pth, 'derivatives', 'scoring', 'scores', 'Manual_Checked'); % where to find scoring files
leadfieldpath   = fullfile(home, 'VS03-SandD-4', 'PM', 'Data_Analysis', 'Brainstorm_db', 'NetsEGI', 'data', 'EGI128_NoWarp', '@intra', 'headmodel_surf_openmeeg.mat'); % where to find leadfield matrices
BIDS.description = []; BIDS.description.Name = 'DM'; % some actions are project specific (e.g., chanlocs import)

% "desc" labels 
% output filenames receive a "desc" label, indicating what was done to them
badchandesc = 'hp';      % hp:  high-pass filtered
filtdesc    = 'hpzc';    % zc:  zapline-plus & cleanline
geddesc     = 'hpzcged'; % ged: gedai 

% Subejct and Session filter
subjects    = {'sub-DM40'};   % {'sub-DM02', '...'} or {} to run on all subjects
sessions    = {};   % {'ses-W1', '...'} or {} to run on all sessions

% Universal default parameters
defaults = [];
defaults.subjectfilter  = subjects;
defaults.sessionfilter  = sessions;
defaults.derivfolder    = derivfolder;
defaults.acqlabel       = acqlabel;
defaults.refresh        = refresh;
defaults.noteegchannels = noteegchannels;
defaults.sfppath        = [];
defaults = namedargs2cell(defaults);



%%% --- PIPELINE START --- %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% %%% Step #0 -> Build leadfield matrices
% build_leadfield_bids(BIDS, 'ProtocolName', 'DROP_Leadfields2', 'ForceReprocess', refresh, ...
%     'QCDir', fullfile(BIDS.pth, 'derivatives\leadfields\figures\electrode-headmodel-fit'))

%%% Step #1 -> Detect flat and bad channels
fails.badchan = bidsfun_detect_badchans(BIDS, defaults{:}, ...
    'badchannumsamples', 50, ...
    'badchancorrthreshold', 0.7, ...
    'badchanstride', 1, ...
    'badchanmaxbrokentime', .3, ... 
    'badchannoisethreshold', 4, ...    
    'flatmaxbrokentime', .3, ...
    'ramsaver', 0, ...
    'targetsrate', targetsrate, ...
    'removeDC', removeDC, ...
    'desc', badchandesc);

%%% Step #2 -> HP filter, remove bad channels, zapline, cleanline
fails.prep = bidsfun_hp_zap_cleanline(BIDS, defaults{:}, ...
    'zapline', 1, ...
    'cleanline', 1, ...
    'zapline2', 0, ...
    'notchfilt', 0, ...    
    'noisefreqs', 50, ...
    'chunkLength', 0, ...
    'noiseCompDetectSigma', 3, ...
    'adaptiveSigma', true, ...
    'cleanlineWinstep', 1, ...
    'cleanlinePad', 2, ...
    'targetsrate', targetsrate, ...
    'removeDC', removeDC, ...
    'badchandesc', badchandesc, ...
    'desc', filtdesc);

%%% Step #2.1 -> Evaluate success of step #1 and #2 
fails.eval = bidsfun_evalfigs(BIDS, defaults{:}, ...
    'targetchannelcount', 124, ...  
    'refresh', refreshFigures, ...
    'scoringpath', scoringpath, ...
    'afterdesc', filtdesc);

%%% Step #3 -> AVG reference, run GEDAI
r = gedai.defaultRuns();
fails.gedai = bidsfun_gedai(BIDS, defaults{:}, ...
    'runs', r, ...
    'RunMode', 'StageSpecific', ...
    'geddesc', geddesc, ...
    'inputdesc', filtdesc, ...
    'leadfielddir', leadfieldpath, ...
    'scoringpath', scoringpath, ...
    'evalplots', false, ...
    'net', net ...            
    );

%%% Step #3.1 -> Evaluate success of step #3
fails.eval = bidsfun_evalfigs(BIDS, defaults{:}, ...
    'targetchannelcount', 124, ...
    'net', net, ...    
    'PlotEpochOverlay', true, ...
    'PlotExponentByStage', true, ...
    'PlotSlopesTimecourse', true, ...
    'avgrefbefore', true, ...
    'avgrefafter', false, ...
    'refresh', refreshFigures, ...
    'scoringpath', scoringpath, ...
    'beforedesc', filtdesc, ...
    'afterdesc', geddesc);    

%%% Output check
out = bidsfun_check_outputs(BIDS, defauls{:}, ...
    'badchandesc', badchandesc, ...
    'filtdesc', filtdesc, ...
    'geddesc', geddesc, ...
    'icadesc', icadesc ...
    );
