%%% Start clean
clearvars
clc; close all

%%% Dependancies
run(['..' filesep 'dependancies.m'])

%%% Define home path
home = '\\vs03.herseninstituut.knaw.nl' % windows
% home = '/home/sleach'; % ubuntu

%%% Build BIDS structure from data folder
%%% BIDS structure contains all pathing and subject information
[BIDS_DROP] = smartcache( ...
    @() bidswizard({'data-drop'}, fullfile(home, 'VS03-SandC-1', 'data', 'nin'), 'rawdata'), ...
    fullfile(pwd, 'BidsFiles', 'BIDS_DROP.mat'), false, {'BIDS_DROP'}); 
BIDS = BIDS_DROP{1}; fails = [];

% Variables
acqlabel        = '';    % acqlabel of EEG file, leave '' if not used
refresh         = false; % re-run when outputs already exist
refreshFigures  = false; % re-run when figures alreaady exist
targetsrate     = 250;   % down-sample to this srate
removeDC        = false; % apply 0.1 Hz high-pass filter?
derivfolder     = 'prep-zc-ged'; % name of output folder within derivatives folder
scoringpath     = fullfile(BIDS.pth, '..', 'derivatives', 'scores', 'final'); % where to find scoring files
leadfieldpath   = fullfile(home, 'VS03-SandD-4', 'PM', 'Data_Analysis', 'Brainstorm_db', 'DROP_Leadfields2', 'data'); % where to find leadfield matrices
BIDS.description = []; BIDS.description.Name = 'DROP'; % some actions are project specific (e.g., chanlocs import)

% "desc" labels 
% output filenames receive a "desc" label, indicating what was done to them
badchandesc = 'hp';      % hp:  high-pass filtered
filtdesc    = 'hpzc';    % zc:  zapline-plus & cleanline
geddesc     = 'hpzcged'; % ged: gedai
icadesc     = 'pamica';  % run-pamica.py's OUT_DESC, i.e. the desc on its *_ica.mat

% Subejct and Session filter
subjects    = {};   % {'sub-drop0001', '...'} or {} to run on all subjects
sessions    = {};   % {'ses-t1', '...'} or {} to run on all sessions



%%% --- PIPELINE START --- %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% Universal default parameters
defaults = [];
defaults.subjectfilter  = subjects;
defaults.sessionfilter  = sessions;
defaults.derivfolder    = derivfolder;
defaults.acqlabel       = acqlabel;
defaults.refresh        = refresh;
defaults = namedargs2cell(defaults);

% %%% Step #0 -> Build leadfield matrices
% build_leadfield_bids(BIDS, 'ProtocolName', 'DROP_Leadfields2', 'ForceReprocess', refresh, ...
%     'SubjectFilter', subjects, 'QCDir', fullfile(BIDS.pth, 'derivatives\leadfields\figures\electrode-headmodel-fit'))

%%% Step #1 -> Detect flat and bad channels
fails.badchan = bidsfun_detect_badchans(BIDS, defaults{:}, ...
    'badchannumsamples', 25, ...
    'badchanstride', 1, ...
    'badchanmaxbrokentime', .3, ...    
    'flatmaxbrokentime', .3, ...
    'ramsaver', 0, ...
    'targetsrate', targetsrate, ...
    'removeDC', removeDC, ...
    'desc', badchandesc);

%%% Step #2 -> HP filter, remove bad channels, zapline, cleanline
fails.prep = bidsfun_hp_zap_cleanline(BIDS, defaults{:}, ...
    'noisefreqs', 50, ...
    'chunkLength', 300, ...
    'noiseCompDetectSigma', 5, ...
    'adaptiveSigma', false, ...
    'cleanlineWinstep', 2, ...
    'cleanlinePad', 2, ...
    'targetsrate', targetsrate, ...
    'removeDC', removeDC, ...
    'badchandesc', badchandesc, ...
    'desc', filtdesc);

%%% Step #2.1 -> Evaluate success of step #1 and #2 
fails.eval = bidsfun_evalfigs(BIDS, defaults{:}, ...
    'refresh', refreshFigures, ...
    'scoringpath', scoringpath, ...
    'backgroundfigs', true, ...
    'afterdesc', filtdesc);

%%% Step #3 -> AVG reference, run GEDAI
r = gedai.defaultRuns();
fails.gedai = bidsfun_gedai(BIDS, defaults{:}, ...
    'runs', r, ...
    'RunMode', 'StageSpecific', ...
    'geddesc', geddesc, ...
    'inputdesc', filtdesc, ...
    'leadfielddir', leadfieldpath, ...
    'scoringpath', scoringpath, ...
    'evalplots', false ...
    );

%%% Step #3.1 -> Evaluate success of step #3
fails.eval = bidsfun_evalfigs(BIDS, defaults{:}, ...
    'PlotEpochOverlay', true, ...
    'PlotExponentByStage', true, ...
    'PlotSlopesTimecourse', true, ...
    'avgrefbefore', true, ...
    'avgrefafter', false, ...
    'refresh', refreshFigures, ...
    'backgroundfigs', true, ...
    'scoringpath', scoringpath, ...
    'beforedesc', filtdesc, ...
    'afterdesc', geddesc);

%%% Step #4 -> Run pAMICA on GPU machine (run-amica.py)

%%% Step #4.1 -> Evaluate success of step #4
fails.eval = bidsfun_evalfigs(BIDS, defaults{:}, ...
    'PlotEpochOverlay', true, ...
    'PlotExponentByStage', true, ...
    'PlotSlopesTimecourse', true, ...
    'PlotICOverview', true, ...
    'avgrefbefore', false, ...
    'avgrefafter', false, ...
    'refresh', refreshFigures, ...
    'backgroundfigs', true, ...
    'scoringpath', scoringpath, ...
    'beforedesc', geddesc, ...    
    'afterdesc', icadesc);


%%% Output check
out = bidsfun_check_outputs(BIDS, defaults{:}, ...
    'badchandesc', badchandesc, ...
    'filtdesc', filtdesc, ...
    'geddesc', geddesc, ...
    'icadesc', icadesc ...
    );