function EEG = chans(EEG, select, opts)
arguments
    EEG
    select   = false;
    opts.net {mustBeMember(opts.net, {'EGI256', 'EGI128'})} = 'EGI256';
end

%%% EGI 256 -> 10-20 mapping  (Cz omitted – absent in standard EGI table)
switch opts.net
    case 'EGI256'
        chanmap = struct( ...
            'Fp1',  37,  ...
            'Fpz',  26,  ...
            'Fp2',  18,  ...
            'F7',   47,  ...
            'F3',   36,  ...
            'Fz',   21,  ...
            'F4',  224,  ...
            'F8',    2,  ...
            'T7',   69,  ...
            'C3',   59,  ...
            'C4',  183,  ...
            'T8',  202,  ...
            'P7',   96,  ...
            'P3',   87,  ...
            'Pz',  101,  ...
            'P4',  153,  ...
            'P8',  170,  ...
            'O1',  116,  ...
            'O2',  150   ...
        );
    case 'EGI128'
        % TBD
end
        
% Structure content
labels1020  = fieldnames(chanmap);
index1020   = struct2array(chanmap);

% Relabel
for iCh = 1:numel(index1020)
    EEG.chanlocs(index1020(iCh)).labels = labels1020{iCh};
end

% Select 10-20 electrodes
if select
    EEG = pop_select(EEG, 'channel', index1020);
end