function eegplot_1020(EEGraw, EEGclean, opts)
% EEGPLOT_1020  Plot EEG data at 10-20 positions for EGI 256-channel caps.
%
%   Temporarily renames EGI channel numbers to 10-20 labels, then opens
%   an eegplot window. If EEGclean is provided it is shown as a red overlay.
%
%   Usage:
%       plots.eegplot_1020(EEGraw)
%       plots.eegplot_1020(EEGraw, EEGclean)
%       plots.eegplot_1020(EEGraw, EEGclean, 'WindowLength', 60)

arguments
    EEGraw
    EEGclean    = []
    opts.WindowLength = 30   % seconds shown per page
    opts.Title        = ''   % overrides auto title
end

%%% EGI 256 -> 10-20 mapping  (Cz omitted – absent in standard EGI table)
egi256_to_1020 = struct( ...
    'Fp1',  37,  ...
    'Fpz',  26,  ...
    'Fp2',  18,  ...
    'F7',   47,  ...
    'F3',   36,  ...
    'Fz',   21,  ...
    'F4',  224,  ...
    'F8',    2,  ...
    'T7',   69,  ...
    'C3',   59,  ...
    'C4',  183,  ...
    'T8',  202,  ...
    'P7',   96,  ...
    'P3',   87,  ...
    'Pz',  101,  ...
    'P4',  153,  ...
    'P8',  170,  ...
    'O1',  116,  ...
    'O2',  150   ...
);

labels1020    = fieldnames(egi256_to_1020);
egi256indices = struct2array(egi256_to_1020);

%%% Work on copies so originals are not mutated
rawCopy = EEGraw;
for iCh = 1:numel(egi256indices)
    rawCopy.chanlocs(egi256indices(iCh)).labels = labels1020{iCh};
end

%%% Plot
if isempty(EEGclean)
    if isempty(opts.Title)
        plotTitle = 'Original EEG (10-20 channels)';
    else
        plotTitle = opts.Title;
    end
    eegplot(rawCopy.data(egi256indices, :), ...
        'srate',     rawCopy.srate,          ...
        'eloc_file', rawCopy.chanlocs(egi256indices), ...
        'winlength', opts.WindowLength,      ...
        'title',     plotTitle);
else
    cleanCopy = EEGclean;
    for iCh = 1:numel(egi256indices)
        cleanCopy.chanlocs(egi256indices(iCh)).labels = labels1020{iCh};
    end

    if isempty(opts.Title)
        plotTitle = 'Black: original  |  Red: cleaned';
    else
        plotTitle = opts.Title;
    end
    eegplot(rawCopy.data(egi256indices, :),  ...
        'data2',     cleanCopy.data(egi256indices, :), ...
        'srate',     rawCopy.srate,                    ...
        'eloc_file', rawCopy.chanlocs(egi256indices),  ...
        'winlength', opts.WindowLength,                ...
        'title',     plotTitle);
end

end
