function name = buildSaveName(r, srate)
    name = sprintf( ...
        'GEDAIBIDS_ICA%s_BBonly%d_LowCutOff%d_BBEpochSize%d_%s_PrcThresh%d_BBMinThresh%d_EnovaChanThresh%d_SENSAI%d_KC%d_b1x%d_b2x%d_Srate%d', ...
        r.ICAtype, r.broadbandOnly, r.GEDAILowCutOffFreq * 10, ...
        r.GEDAIBroadbandEpochSize, r.GEDAIMode, r.percentileThreshold, ...
        r.BBMinThreshold, r.GEDAIEnovaChannelThreshold, r.computeSENSAI, ...
        r.WeightKC * 100, round(r.boost1 * 10), round(r.boost2 * 10), srate);
end
