function name = buildSaveName(r, srate)
    name = sprintf( ...
        'ICA%s_BBonly%d_LCO%d_BBE%d_%s_PT%d_BMT%d_ECT%d_SENSAI%d_KC%d_b1x%d_b2x%d_sr%d', ...
        r.ICAtype, r.broadbandOnly, r.GEDAILowCutOffFreq * 10, ...
        r.GEDAIBroadbandEpochSize, r.GEDAIMode, r.percentileThreshold, ...
        r.BBMinThreshold, r.GEDAIEnovaChannelThreshold, r.computeSENSAI, ...
        r.WeightKC * 100, round(r.boost1 * 10), round(r.boost2 * 10), srate);
end
