function runs = defaultRuns()
% DEFAULTRUNS  Default GEDAI run configuration.
%
% Cleaning strength is set per sleep stage through the two stage-keyed dictionaries.
% They must cover every stage digit any runmode groups over (-3, -2, 0, 1). N1 (-1) is
% not included: killN1 always reassigns N1 epochs to a neighbouring stage before GEDAI
% runs, so -1 never appears in a stage group and never needs a cleaning strength of its
% own. There is no scalar fallback: a stage without an entry is an error, not a silent
% default.

    N3 = -3; N2 = -2; REM = 0; Wake = 1;
    stages = [N3, N2, REM, Wake];

    runs = {struct( ...
        'GEDAIMode_dict',             dictionary(stages, ["auto",  "auto",  "auto",  "auto+"]), ...
        'GEDAIModeBB_dict',           dictionary(stages, ["auto-", "auto-", "auto-", "auto+"]), ...
        'GEDAILowCutOffFreq',         0.1, ...
        'GEDAIEpochSize',             12, ...
        'GEDAIBroadbandEpochSize',    10, ...
        'boost1',                     1, ...
        'boost2',                     1, ...
        'broadbandOnly',              false, ...
        'percentileThreshold',        98, ...
        'WeightKC',                   0, ...
        'BBMinThreshold',             -2, ...
        'computeSENSAI',              false, ...
        'GEDAIEnovaChannelThreshold', Inf, ...
        'ICAtype',                    'none')};
end
