function runs = defaultRuns()
    N3 = -3; N2 = -2; REM = 0; Wake = 1;
    runs = {struct( ...
        'GEDAIMode',                  'auto', ...
        'GEDAIMode_dict',             dictionary([N3, N2, REM, Wake], ["auto", "auto", "auto", "auto"]), ...
        'GEDAILowCutOffFreq',         0.1, ...
        'GEDAIEpochSize',             12, ...
        'GEDAIBroadbandEpochSize',    10, ...
        'boost1',                     1, ...
        'boost2',                     1, ...
        'broadbandOnly',              false, ...
        'percentileThreshold',        98, ...
        'WeightKC',                   0, ...
        'BBMinThreshold',             -2, ...
        'computeSENSAI',              false, ...
        'GEDAIEnovaChannelThreshold', Inf, ...
        'ICAtype',                    'none')};
end
