function runs = defaultRuns()
    runs = {struct( ...
        'GEDAIMode',                  'auto', ...
        'GEDAILowCutOffFreq',         0.1, ...
        'GEDAIEpochSize',             12, ...
        'GEDAIBroadbandEpochSize',    10, ...
        'boost1',                     1, ...
        'boost2',                     1, ...
        'broadbandOnly',              false, ...
        'percentileThreshold',        98, ...
        'WeightKC',                   0, ...
        'BBMinThreshold',             -2, ...
        'computeSENSAI',              false, ...
        'GEDAIEnovaChannelThreshold', Inf, ...
        'ICAtype',                    'none')};
end
